version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file LF1-spec.yaml --s3-bucket b2photoszj --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - LF1-spec.yaml
    - outputsamtemplate.yml
